name: releasing

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Check tag version
        run: |
          .github/bin/check-version.sh "${GITHUB_REF#refs/tags/v}"

  build:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Install Python dependencies
        run: make deps-py
      - name: Install JS dependencies
        run: make deps-js
      - name: Build wheels
        run: make wheels
      - name: Extract changelog
        run: |
          .github/bin/extract-changelog.py ${{ github.ref_name }} /tmp/changelog.md
      - uses: actions/upload-artifact@v4
        name: Upload build artifacts
        with:
          name: wheels
          path: ./dist/*.whl
      - uses: actions/upload-artifact@v4
        name: Upload changelog
        with:
          name: changelog
          path: /tmp/changelog.md

  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish release
        run: >-
          gh release create
          --repo ${{ github.repository }}
          --title ${{ github.ref_name }}
          --notes-file changelog/changelog.md
          ${{ github.ref_name }}
          wheels/*
        env:
          GH_TOKEN: ${{ github.token }}
